# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 168ba7783ec45a0eee9f7e0b8898965507a12fea6f756001e9e31b968b3fa863e383ec2ce2a1224b0a8232b708bbb96e810afe11b8b46ea1d1df7c564d496d83

test:
  secret_key_base: 1c4b78e07c55f13ce59851804eb7aa49d00d8af9e7e18b5faed002b7c0179b73e92d415ecaf8a83b1443739e8cd8f9c20f4f3959b41a7754ad74392f77e6824b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
